[package]
name = "nauto_drivers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
async-ssh2-tokio = "0.11"
nauto_model = { path = "../nauto_model" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

