[package]
name = "ssh_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-ssh2-tokio = "0.11"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

