[package]
name = "tauri_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "1", features = ["api-all"] }

[build-dependencies]
tauri-build = { version = "1", features = [] }

